services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: emotion-prediction-api

    ports:
      - "8000:8000"

    volumes:
      - ./expirements:/app/expirements:ro
      - ./data:/app/data:ro
      - ./logs:/app/logs

    environment:
      CONFIG_PATH: /app/config.ini
      CHECKPOINT_PATH: /app/expirements/dog_emotion_efficientnet_best.pth

    restart: unless-stopped